notifications:
  email: false
  slack: exist-db:IXzUdqA0n11cnxaDz43ZQgdX

language: node_js

node_js:
  - "node"
  - "10"

dist: xenial
# temporary see https://github.com/cypress-io/cypress/issues/4069
addons:
  apt:
    packages:
    - libgconf-2-4
env:
  - img=existdb/existdb:latest spec="5.x.x/**"
  - img=existdb/existdb:release spec="5.x.x/**"
  - img=existdb/existdb:4.7.1 spec="4.x.x/**"

services:
  - docker

cache:
  npm: true
  directories:
    - ~/.cache

before_install:
  - docker pull $img
  - docker create  --name exist-ci -p 8080:8080 $img

install:
  - npm ci
  - ant production-xar
  - docker cp build/usermanager-*-prod.xar exist-ci:exist/autodeploy

before_script:
  - docker start exist-ci
  # exist needs time
  - sleep 30
  - docker ps

script:
  - cypress run --record --key $CYPRESS_RECORD_KEY --spec \'cypress/integration/${spec}\'
